# Generated by Django 4.2.7 on 2023-12-22 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_id', models.BigIntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Passed'), (2, 'Failed')], default=0)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('audit_time', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=1023)),
                ('file', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
