# Generated by Django 4.2.7 on 2023-12-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='research_name',
            field=models.CharField(default='KYX', max_length=127),
            preserve_default=False,
        ),
    ]
