# Generated by Django 4.2.7 on 2023-12-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_application_research_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
