# Generated by Django 4.2.7 on 2023-12-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='research_name',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
