# Generated by Django 4.2.7 on 2023-12-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_message_content_message_research_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link_content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='link_id',
            field=models.IntegerField(null=True),
        ),
    ]
