# Generated by Django 4.2.7 on 2023-12-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_link_content_message_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='research_name',
        ),
    ]
