# Generated by Django 4.2.7 on 2023-12-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_message_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='research_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
