# Generated by Django 4.2.7 on 2023-12-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_message_research_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.IntegerField(choices=[(0, 'Claim Review'), (1, 'Follow Update'), (2, 'Works Transfer'), (3, 'Transfer Response')], default=1),
        ),
        migrations.AddField(
            model_name='message',
            name='work_type',
            field=models.IntegerField(choices=[(0, 'Patent'), (1, 'Project'), (2, 'Reward')], null=True),
        ),
    ]
