# Generated by Django 4.2.7 on 2023-12-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_follow_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intro',
            field=models.TextField(default='暂无简介'),
        ),
    ]
