# Generated by Django 4.2.7 on 2023-12-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userprofile_follow_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follow_list',
            field=models.JSONField(default=dict),
        ),
    ]
