# Generated by Django 4.2.7 on 2023-12-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_userprofile_follow_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="collect_list",
            field=models.JSONField(default=[]),
        ),
    ]
