# Generated by Django 4.2.7 on 2023-11-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Concepts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Institutions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Sources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Works",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("publication_date", models.DateField()),
                ("language", models.CharField(max_length=2)),
                ("type", models.CharField(max_length=32)),
                ("authors", models.JSONField()),
                ("cited_by_count", models.IntegerField()),
                ("biblio", models.JSONField()),
                ("keywords", models.JSONField()),
                ("concepts", models.JSONField()),
                ("locations", models.JSONField()),
                ("referenced_works", models.JSONField()),
                ("related_works", models.JSONField()),
                ("abstract_inverted_index", models.JSONField()),
                ("counts_by_year", models.JSONField()),
                ("updated_date", models.DateField()),
                ("created_date", models.DateField()),
            ],
        ),
    ]
