# Generated by Django 4.2.7 on 2023-12-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concepts",
            name="image_url",
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="institutions",
            name="homepage_url",
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="institutions",
            name="image_url",
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="sources",
            name="homepage_url",
            field=models.URLField(max_length=512, null=True),
        ),
    ]
