# Generated by Django 4.2.7 on 2023-12-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0002_alter_concepts_image_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authors",
            old_name="concepts",
            new_name="x_concepts",
        ),
    ]
