# Generated by Django 4.2.7 on 2023-11-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0002_author_concepts_institution_source"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Author",
            new_name="Authors",
        ),
        migrations.RenameModel(
            old_name="Institution",
            new_name="Institutions",
        ),
        migrations.RenameModel(
            old_name="Source",
            new_name="Sources",
        ),
        migrations.RenameModel(
            old_name="Work",
            new_name="Works",
        ),
    ]
