# Generated by Django 4.2.7 on 2023-12-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0003_rename_concepts_authors_x_concepts"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Authors",
        ),
        migrations.DeleteModel(
            name="Concepts",
        ),
        migrations.DeleteModel(
            name="Institutions",
        ),
        migrations.DeleteModel(
            name="Sources",
        ),
        migrations.DeleteModel(
            name="Works",
        ),
    ]
