# Generated by Django 4.2.7 on 2023-11-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0004_alter_works_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="works",
            name="title",
            field=models.CharField(max_length=256),
        ),
    ]
