# Generated by Django 4.2.7 on 2023-11-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("science", "0005_alter_works_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="works",
            name="title",
            field=models.CharField(max_length=511),
        ),
    ]
