from django.db import models


# Create your models here.

class Works(models.Model):
    id = models.BigIntegerField(primary_key=True)
    title = models.CharField(max_length=511)
    publication_date = models.DateField()
    language = models.CharField(max_length=2, null=True)
    type = models.CharField(max_length=32)
    authors = models.JSONField()
    cited_by_count = models.IntegerField()
    biblio = models.JSONField()
    keywords = models.JSONField()
    concepts = models.JSONField()
    locations = models.JSONField()
    referenced_works = models.JSONField()
    related_works = models.JSONField()
    abstract_inverted_index = models.JSONField(null=True)
    counts_by_year = models.JSONField()
    updated_date = models.DateTimeField()
    created_date = models.DateField()


class Authors(models.Model):
    id = models.BigIntegerField(primary_key=True)
    orcid = models.CharField(max_length=64)
    display_name = models.CharField(max_length=128)
    works_count = models.IntegerField()
    cited_by_count = models.IntegerField()
    twoyr_mean_citedness = models.FloatField()
    h_index = models.IntegerField()
    i10_index = models.IntegerField()
    last_known_institution = models.JSONField()
    concepts = models.JSONField()
    counts_by_year = models.JSONField()
    updated_date = models.DateTimeField()
    created_date = models.DateField()


class Sources(models.Model):
    id = models.BigIntegerField(primary_key=True)
    display_name = models.CharField(max_length=255)
    host_organization = models.BigIntegerField()
    host_organization_name = models.CharField(max_length=255)
    works_count = models.IntegerField()
    cited_by_count = models.IntegerField()
    twoyr_mean_citedness = models.FloatField()
    h_index = models.IntegerField()
    i10_index = models.IntegerField()
    wikidata = models.URLField()
    homepage_url = models.URLField()
    country_code = models.CharField(max_length=2)
    type = models.CharField(max_length=32)
    concepts = models.JSONField()
    counts_by_year = models.JSONField()
    updated_date = models.DateTimeField()
    created_date = models.DateField()


class Institutions(models.Model):
    id = models.BigIntegerField(primary_key=True)
    ror = models.URLField()
    display_name = models.CharField(max_length=255)
    country_code = models.CharField(max_length=2)
    type = models.CharField(max_length=32)
    homepage_url = models.URLField()
    image_url = models.URLField()
    works_count = models.IntegerField()
    cited_by_count = models.IntegerField()
    twoyr_mean_citedness = models.FloatField()
    h_index = models.IntegerField()
    i10_index = models.IntegerField()
    wikidata = models.URLField()
    geo = models.JSONField()
    associated_institutions = models.JSONField()
    counts_by_year = models.JSONField()
    concepts = models.JSONField()
    updated_date = models.DateTimeField()
    created_date = models.DateField()


class Concepts(models.Model):
    id = models.BigIntegerField(primary_key=True)
    wikidata = models.URLField()
    display_name = models.CharField(max_length=255)
    level = models.SmallIntegerField()
    description = models.TextField()
    works_count = models.IntegerField()
    cited_by_count = models.IntegerField()
    twoyr_mean_citedness = models.FloatField()
    h_index = models.IntegerField()
    i10_index = models.IntegerField()
    image_url = models.URLField()
    ancestors = models.JSONField()
    related_concepts = models.JSONField()
    counts_by_year = models.JSONField()
    updated_date = models.DateTimeField()
    created_date = models.DateField()
