# Generated by Django 4.2.7 on 2023-12-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=64)),
                ('authors', models.TextField()),
                ('authors_r', models.JSONField(default={})),
                ('year', models.IntegerField()),
                ('number', models.CharField(default='', max_length=32)),
                ('authorized_institutions', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('application_code', models.CharField(max_length=10)),
                ('authors', models.TextField()),
                ('authors_r', models.JSONField(default={})),
                ('supporting_units', models.CharField(max_length=128)),
                ('funds', models.FloatField()),
                ('abstract_c', models.TextField()),
                ('abstract_e', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=64)),
                ('authors', models.TextField()),
                ('authors_r', models.JSONField(default={})),
                ('year', models.IntegerField()),
                ('award_institution', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
