# Generated by Django 4.2.7 on 2023-12-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('authors', models.JSONField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('application_code', models.CharField(max_length=8)),
                ('authors', models.JSONField()),
                ('supporting_units', models.CharField(max_length=64)),
                ('funds', models.FloatField()),
                ('abstract', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('authors', models.JSONField()),
                ('year', models.IntegerField()),
                ('award_institution', models.CharField(max_length=64)),
            ],
        ),
    ]
