# Generated by Django 4.2.7 on 2023-12-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='authors_r',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='authors_r',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='reward',
            name='authors_r',
            field=models.JSONField(default=dict),
        ),
    ]
