# Generated by Django 4.2.7 on 2023-12-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abstract_c',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='abstract_e',
            field=models.BinaryField(),
        ),
    ]
