# Generated by Django 4.2.7 on 2023-12-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0002_alter_project_abstract_c_alter_project_abstract_e'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
    ]
