# Generated by Django 4.2.7 on 2023-12-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0002_alter_patent_authors_r_alter_project_authors_r_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='reward',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
