# Generated by Django 4.2.7 on 2023-12-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0003_remove_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='supporting_units',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
