# Generated by Django 4.2.7 on 2023-12-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0004_alter_project_supporting_units_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abstract_c',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='abstract_e',
            field=models.TextField(),
        ),
    ]
