# Generated by Django 4.2.7 on 2023-12-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0002_alter_patent_authors_r_alter_reward_authors_r'),
        ('additional', '0004_alter_patent_title_alter_reward_title'),
    ]

    operations = [
    ]
