# Generated by Django 4.2.7 on 2023-12-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0005_merge_20231223_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='children_p',
            field=models.ManyToManyField(to='additional.patent'),
        ),
        migrations.AddField(
            model_name='project',
            name='children_r',
            field=models.ManyToManyField(to='additional.reward'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reward',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
