# Generated by Django 4.2.7 on 2023-12-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0005_alter_project_abstract_c_alter_project_abstract_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='authorized_institutions',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='patent',
            name='authors_r',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='patent',
            name='number',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='reward',
            name='authors_r',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='patent',
            name='authors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patent',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='reward',
            name='authors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reward',
            name='award_institution',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='reward',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reward',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
