# Generated by Django 4.2.7 on 2023-12-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0006_project_children_p_project_children_r_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
