# Generated by Django 4.2.7 on 2023-12-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0006_patent_authorized_institutions_patent_authors_r_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='authors_r',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='project',
            name='authors',
            field=models.TextField(),
        ),
    ]
